### ISSUE TITLE
Question about headers

### ISSUE THREAD

**Issue by davidsills** [AdrianCitu/GenericCSRFFilter#1]
Sorry if this question is naive. Your CRSF filter appears to be quite good, but doesn't deal with one issue: how do I ensure that the browser will send along the appropriate header when requesting a new page? If it doesn't, your filter is worse than useless, because EVERYTHING will look like a CSRF attack! I'm sure the answer is implicit in something I don't know, but I'd love to be informed if you are willing. Thanks! (davidsills@yahoo.com)

**Comment by AdrianCitu** [comment]
Hello David,
You are completely right; if the header is not filled then all it will look like a CSRF attack. Some JS frameworks like Angular are implementing out of the box the fill of the header with the content of a specific cookie. (Angular is looking by default to a cookie called X-XSRF-TOKEN). 
So my CSRF filter is supposing that on the client (browser) side something will do the job of filling the right header.

hope it helps and is clearer;
Sorry for my shameless self-promotion; if you need more details about how the filter works you can check this blog ticket: https://adriancitu.com/2017/01/16/a-java-implementation-of-csrf-mitigation-using-double-submit-cookie-pattern/

thx,
Adrian
